### ISSUE TITLE
Checkbox problem

### ISSUE THREAD

**Issue by AlbertSuarez** [BlunchDev/blunch_android#46] opened 2016-04-28 06:45 UTC
In the GetPaymentMenu Activity, if the user select some dishes quickly, the app blocks and stops.

**Comment by quim-motger** [comment] 2016-04-28 06:47
I don't know if it has anything to do with the generation of the view, but yesterday I saw the checkboxes in this activity are generated in a VERY complex way - it is really simple to generate a checkbox list with listeners in the same activity, with just a few lines of code. 

I'm not sure if refactoring this generation will solve the problem, but certainly this is a task that should be performed. I can take care of it if you want to.

**Comment by quim-motger** [comment] 2016-04-28 06:49
I'm not assigning this for next milestone as it is not strictly necessary for the demo, but let's keep it in mind

**Comment by casassg** [comment] 2016-04-28 06:53
We need to refactor and simplificate a little bit more of the inerface logic

**Comment by quim-motger** [comment] 2016-04-28 06:58
I think mainly the problem is that views and layout definition must be defined as much as possible in the layout files (xml files). Dynamic generation of views in java classes should be only used when necessary (i.e., for adapters or conditional styling).

That way development is much easier, especially when you need to modify layouts you didn't define - maybe in the next sprint review we could spend a few minutes in trying to make an agreement on this.

**Closed** 2016-05-10 21:27 UTC
Labels: bug
